/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author sony
 */
public class Siswa extends javax.swing.JFrame {
private Connection con;
private Statement stat;
private ResultSet res;
private String t, keterangan;
private DefaultTableModel dtm;
String nis,nama,alamat,jk,agama,tanggal,telepon,asal,nilai;
    /**
     * Creates new form Daftar
     */
    public Siswa() {
        initComponents();
        setTitle("FORM SISWA");
        koneksi ();
        clear ();
        tabel ();
        id();
    }
    
    private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("NIS");
        t.addColumn("Nama");
        t.addColumn("Alamat");
        t.addColumn("Jenis Kelamin");
        t.addColumn("Agama");
        t.addColumn("Tanggal Lahir");
        t.addColumn("Telepon");
        t.addColumn("Asal Sekolah");
        t.addColumn("Nilai Akhir");
        rr_tablesiswa.setModel(t); try{ res= stat.executeQuery("select * from siswa");
      while (res.next()) {
      t.addRow(new Object[]{ 
      res.getString("nis"),
      res.getString("nama"),
      res.getString("alamat"),
      res.getString("jenis_kelamin"),
      res.getString("agama"),
      res.getString("tanggal_lahir"),
      res.getString("telepon"),
      res.getString("asal_sekolah"),
      res.getString("nilai_akhir")
        });}
      
}catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);}    
    }
    
    private void koneksi (){
     try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://localhost/db_ppdb", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }
    

    
    private void clear(){
     rr_nis.setText("");
     rr_nama.setText("");
     rr_telepon.setText("");
     rr_alamat.setText("");
     rr_asalsekolah.setText("");
     rr_nilaiakhir.setText("");
     rr_tanggal.setText("");
     rr_nis.setEnabled(false);
    }
    
   
    
    private void id()
    {
       try {
            String sql="select * from siswa order by nis desc";
            stat=con.createStatement();
            res=stat.executeQuery(sql);
            if (res.next()) {
                String id = res.getString("nis").substring(1);
                String AN = "" + (Integer.parseInt(id) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}

               rr_nis.setText("N" + Nol + AN);
            } else {
               rr_nis.setText("N0211");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
     }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rr_nama = new javax.swing.JTextField();
        rr_nis = new javax.swing.JTextField();
        rr_telepon = new javax.swing.JTextField();
        rr_nilaiakhir = new javax.swing.JTextField();
        rr_asalsekolah = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        rr_tablesiswa = new javax.swing.JTable();
        rr_tambah = new javax.swing.JButton();
        rr_ubah = new javax.swing.JButton();
        rr_hapus = new javax.swing.JButton();
        rr_kembali = new javax.swing.JButton();
        rr_alamat = new javax.swing.JTextField();
        rr_jk = new javax.swing.JComboBox<>();
        rr_cetak = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rr_agama = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        rr_tanggal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("NIS");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Telepon");

        jLabel6.setText("Asal Sekolah");

        jLabel7.setText("Nilai Akhir");

        rr_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rr_nisActionPerformed(evt);
            }
        });
        rr_nis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rr_nisKeyTyped(evt);
            }
        });

        rr_telepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rr_teleponKeyTyped(evt);
            }
        });

        rr_nilaiakhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rr_nilaiakhirKeyTyped(evt);
            }
        });

        rr_tablesiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Alamat", "Jenis Kelamin", "Agama", "Tanggal Lahir", "Telepon", "Asal Sekolah", "Nilai Akhir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rr_tablesiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rr_tablesiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(rr_tablesiswa);
        if (rr_tablesiswa.getColumnModel().getColumnCount() > 0) {
            rr_tablesiswa.getColumnModel().getColumn(0).setMinWidth(80);
            rr_tablesiswa.getColumnModel().getColumn(0).setMaxWidth(80);
            rr_tablesiswa.getColumnModel().getColumn(3).setMinWidth(80);
            rr_tablesiswa.getColumnModel().getColumn(3).setMaxWidth(80);
            rr_tablesiswa.getColumnModel().getColumn(8).setMinWidth(80);
            rr_tablesiswa.getColumnModel().getColumn(8).setMaxWidth(80);
        }

        rr_tambah.setText("Tambah");
        rr_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rr_tambahActionPerformed(evt);
            }
        });

        rr_ubah.setText("Ubah");
        rr_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rr_ubahActionPerformed(evt);
            }
        });

        rr_hapus.setText("Hapus");
        rr_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rr_hapusActionPerformed(evt);
            }
        });

        rr_kembali.setText("Kembali");
        rr_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rr_kembaliActionPerformed(evt);
            }
        });

        rr_jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Perempuan", "Laki-Laki" }));

        rr_cetak.setText("Cetak");
        rr_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rr_cetakActionPerformed(evt);
            }
        });

        jLabel8.setText("Agama");

        rr_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Islam", "Kristen", "Katolik", "Hindu", "Buddha" }));

        jLabel9.setText("Tanggal Lahir");

        rr_tanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rr_tanggalKeyTyped(evt);
            }
        });

        jLabel10.setText("e.g : 01 Januari 2022");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 337, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rr_tambah)
                        .addGap(32, 32, 32)
                        .addComponent(rr_ubah)
                        .addGap(30, 30, 30)
                        .addComponent(rr_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(rr_cetak)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rr_kembali)
                        .addGap(76, 76, 76))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rr_nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addComponent(rr_nis, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(rr_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rr_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rr_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rr_asalsekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rr_nilaiakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(rr_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(rr_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rr_nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(rr_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rr_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rr_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(rr_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rr_jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(rr_asalsekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rr_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rr_nilaiakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rr_cetak)
                    .addComponent(rr_hapus)
                    .addComponent(rr_ubah)
                    .addComponent(rr_tambah))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(rr_kembali)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rr_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rr_nisActionPerformed
         try{
            res=stat.executeQuery("select * from siswa where "+ "nis='" + rr_nis.getText()
                +"'" ); while (res.next())
                { rr_nama.setText(res.getString("nama"));
                rr_alamat.setText(res.getString("alamat"));
                rr_jk.setSelectedItem(res.getString("jenis_kelamin"));
                rr_agama.setSelectedItem(res.getString("agama"));
                rr_tanggal.setText(res.getString("tanggal_lahir"));
                rr_telepon.setText(res.getString("telepon"));
                rr_asalsekolah.setText(res.getString("asal_sekolah"));
                rr_nilaiakhir.setText(res.getString("nilai_akhir"));
                }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
           
    }//GEN-LAST:event_rr_nisActionPerformed

    private void rr_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rr_ubahActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin mengedit data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
        nis=rr_nis.getText();
        nama=rr_nama.getText();
        alamat=rr_alamat.getText();
        jk=rr_jk.getItemAt(rr_jk.getSelectedIndex()).toString();
        agama=rr_agama.getItemAt(rr_agama.getSelectedIndex()).toString();
        tanggal=rr_asalsekolah.getText();
        telepon=rr_telepon.getText();
        asal=rr_asalsekolah.getText();
        nilai=rr_nilaiakhir.getText();
        try {
            String sql=" update  siswa "
            + "set nama='"+ nama +"',"
            + "alamat='"+ alamat +"',"
            + "jenis_kelamin='"+ jk +"',"
            + "agama='"+ agama +"',"
            + "tanggal_lahir='"+ tanggal +"',"
            + "telepon='"+ telepon +"',"
            + "asal_sekolah='"+ asal +"',"
            + "nilai_akhir='"+ nilai
            + "' where nis='"+ nis +"'";
            stat=con.createStatement();
            stat.execute(sql);
            new Siswa().setVisible(true);
            dispose();
            JOptionPane.showMessageDialog(null,"Data Berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Tidak Ada Data Yang Di Edit ....!! \n"
                +e.getMessage());
        }
    }//GEN-LAST:event_rr_ubahActionPerformed

    private void rr_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rr_tambahActionPerformed
    try {
         stat.executeUpdate("insert into siswa values ("
             + "'" + rr_nis.getText()+"',"
             + "'" + rr_nama.getText()+"',"
             + "'" + rr_alamat.getText()+"',"
             + "'" + rr_jk.getSelectedItem()+ "',"
             + "'" + rr_agama.getSelectedItem()+ "',"
             + "'" + rr_tanggal.getText()+ "',"
             + "'" + rr_telepon.getText()+"',"
             + "'" + rr_asalsekolah.getText()+"',"
             + "'" + rr_nilaiakhir.getText()+"')");
         clear();
         JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
         new Siswa().setVisible(true);
         dispose();
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data! : "+e);
        }
    }//GEN-LAST:event_rr_tambahActionPerformed

    private void rr_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rr_hapusActionPerformed
        int ok=JOptionPane.showConfirmDialog(null, "Apakah yakin ingin menghapus?", "Confirmation", 
                JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
         try{
             String sql="delete from siswa where nis='"+rr_nis.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             clear();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new Siswa().setVisible(true);
             dispose();
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal");
         }
        }
    }//GEN-LAST:event_rr_hapusActionPerformed

    private void rr_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rr_kembaliActionPerformed
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_rr_kembaliActionPerformed

    private void rr_tablesiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rr_tablesiswaMouseClicked
    if (evt.getClickCount()== 1){
        rr_nis.setText(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),0)));
        rr_nama.setText(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),1)));
        rr_alamat.setText(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),2)));
        rr_jk.setSelectedItem(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),3)));
        rr_agama.setSelectedItem(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),4)));
        rr_tanggal.setText(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),5)));
        rr_telepon.setText(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),6)));
        rr_asalsekolah.setText(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),7)));
        rr_nilaiakhir.setText(String.valueOf(rr_tablesiswa.getValueAt(rr_tablesiswa.getSelectedRow(),8)));
    }
    }//GEN-LAST:event_rr_tablesiswaMouseClicked

    private void rr_nisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rr_nisKeyTyped
        char RR=evt.getKeyChar();
        if(!(Character.isDigit(RR)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rr_nisKeyTyped

    private void rr_teleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rr_teleponKeyTyped
        char RR=evt.getKeyChar();
        if(!(Character.isDigit(RR)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rr_teleponKeyTyped

    private void rr_nilaiakhirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rr_nilaiakhirKeyTyped
        char RR=evt.getKeyChar();
        if(!(Character.isDigit(RR)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rr_nilaiakhirKeyTyped

    private void rr_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rr_cetakActionPerformed
     JOptionPane.showMessageDialog(rootPane, "Mohon tunggu sebentar!","Information",JOptionPane.INFORMATION_MESSAGE);
     try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("reportsiswa.jasper"), null, Koneksi.getConnection());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_rr_cetakActionPerformed

    private void rr_tanggalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rr_tanggalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_rr_tanggalKeyTyped

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> rr_agama;
    public javax.swing.JTextField rr_alamat;
    public javax.swing.JTextField rr_asalsekolah;
    private javax.swing.JButton rr_cetak;
    private javax.swing.JButton rr_hapus;
    private javax.swing.JComboBox<String> rr_jk;
    private javax.swing.JButton rr_kembali;
    public javax.swing.JTextField rr_nama;
    public javax.swing.JTextField rr_nilaiakhir;
    public javax.swing.JTextField rr_nis;
    public javax.swing.JTable rr_tablesiswa;
    private javax.swing.JButton rr_tambah;
    public javax.swing.JTextField rr_tanggal;
    public javax.swing.JTextField rr_telepon;
    private javax.swing.JButton rr_ubah;
    // End of variables declaration//GEN-END:variables
}
